# Uncomment this line to define a global platform for your project
platform :ios,  '12.0'
use_frameworks!

target 'AirbusNavDisplay' do

# debug only pods
pod 'Reveal-SDK', :configurations => ['Debug']

end
